alias ll='ls -l'
alias la='ls -a'
alias jjl=' jj |  less'
alias nv='nvim'
alias h='atuin search'
alias bcat='bat -p --paging=never'
alias bn='bat --style="numbers,header"'
alias dl='lsd'
alias ez='/usr/bin/eza --icons'
alias el='eza -lhg --icons'
alias ea='eza -lha --sort=type --icons --group-directories-first'
alias et='eza --tree --level=3 --icons' 
